#!/bin/sh

var -k country AF "Afghanistan"
var -k country AX "Åland Islands"
var -k country AL "Albania"
var -k country DZ "Algeria"
var -k country AS "American Samoa"
var -k country AD "Andorra"
var -k country AO "Angola"
var -k country AI "Anguilla"
var -k country AQ "Antarctica"
var -k country AG "Antigua and Barbuda"
var -k country AR "Argentina"
var -k country AM "Armenia"
var -k country AW "Aruba"
var -k country AU "Australia"
var -k country AT "Austria"
var -k country AZ "Azerbaijan"
var -k country BS "Bahamas"
var -k country BH "Bahrain"
var -k country BD "Bangladesh"
var -k country BB "Barbados"
var -k country BY "Belarus"
var -k country BE "Belgium"
var -k country BZ "Belize"
var -k country BJ "Benin"
var -k country BM "Bermuda"
var -k country BT "Bhutan"
var -k country BO "Bolivia, Plurinational State of"
var -k country BQ "Bonaire, Sint Eustatius and Saba"
var -k country BA "Bosnia and Herzegovina"
var -k country BW "Botswana"
var -k country BV "Bouvet Island"
var -k country BR "Brazil"
var -k country IO "British Indian Ocean Territory"
var -k country BN "Brunei Darussalam"
var -k country BG "Bulgaria"
var -k country BF "Burkina Faso"
var -k country BI "Burundi"
var -k country KH "Cambodia"
var -k country CM "Cameroon"
var -k country CA "Canada"
var -k country CV "Cape Verde"
var -k country KY "Cayman Islands"
var -k country CF "Central African Republic"
var -k country TD "Chad"
var -k country CL "Chile"
var -k country CN "China"
var -k country CX "Christmas Island"
var -k country CC "Cocos (Keeling) Islands"
var -k country CO "Colombia"
var -k country KM "Comoros"
var -k country CG "Congo"
var -k country CD "Congo, the Democratic Republic of the"
var -k country CK "Cook Islands"
var -k country CR "Costa Rica"
var -k country CI "Côte d'Ivoire"
var -k country HR "Croatia"
var -k country CU "Cuba"
var -k country CW "Curaçao"
var -k country CY "Cyprus"
var -k country CZ "Czech Republic"
var -k country DK "Denmark"
var -k country DJ "Djibouti"
var -k country DM "Dominica"
var -k country DO "Dominican Republic"
var -k country EC "Ecuador"
var -k country EG "Egypt"
var -k country SV "El Salvador"
var -k country GQ "Equatorial Guinea"
var -k country ER "Eritrea"
var -k country EE "Estonia"
var -k country ET "Ethiopia"
var -k country FK "Falkland Islands (Malvinas)"
var -k country FO "Faroe Islands"
var -k country FJ "Fiji"
var -k country FI "Finland"
var -k country FR "France"
var -k country GF "French Guiana"
var -k country PF "French Polynesia"
var -k country TF "French Southern Territories"
var -k country GA "Gabon"
var -k country GM "Gambia"
var -k country GE "Georgia"
var -k country DE "Germany"
var -k country GH "Ghana"
var -k country GI "Gibraltar"
var -k country GR "Greece"
var -k country GL "Greenland"
var -k country GD "Grenada"
var -k country GP "Guadeloupe"
var -k country GU "Guam"
var -k country GT "Guatemala"
var -k country GG "Guernsey"
var -k country GN "Guinea"
var -k country GW "Guinea-Bissau"
var -k country GY "Guyana"
var -k country HT "Haiti"
var -k country HM "Heard Island and McDonald Islands"
var -k country VA "Holy See (Vatican City State)"
var -k country HN "Honduras"
var -k country HK "Hong Kong"
var -k country HU "Hungary"
var -k country IS "Iceland"
var -k country IN "India"
var -k country ID "Indonesia"
var -k country IR "Iran, Islamic Republic of"
var -k country IQ "Iraq"
var -k country IE "Ireland"
var -k country IM "Isle of Man"
var -k country IL "Israel"
var -k country IT "Italy"
var -k country JM "Jamaica"
var -k country JP "Japan"
var -k country JE "Jersey"
var -k country JO "Jordan"
var -k country KZ "Kazakhstan"
var -k country KE "Kenya"
var -k country KI "Kiribati"
var -k country KP "Korea, Democratic People's Republic of"
var -k country KR "Korea, Republic of"
var -k country KW "Kuwait"
var -k country KG "Kyrgyzstan"
var -k country LA "Lao People's Democratic Republic"
var -k country LV "Latvia"
var -k country LB "Lebanon"
var -k country LS "Lesotho"
var -k country LR "Liberia"
var -k country LY "Libya"
var -k country LI "Liechtenstein"
var -k country LT "Lithuania"
var -k country LU "Luxembourg"
var -k country MO "Macao"
var -k country MK "Macedonia, the Former Yugoslav Republic of"
var -k country MG "Madagascar"
var -k country MW "Malawi"
var -k country MY "Malaysia"
var -k country MV "Maldives"
var -k country ML "Mali"
var -k country MT "Malta"
var -k country MH "Marshall Islands"
var -k country MQ "Martinique"
var -k country MR "Mauritania"
var -k country MU "Mauritius"
var -k country YT "Mayotte"
var -k country MX "Mexico"
var -k country FM "Micronesia, Federated States of"
var -k country MD "Moldova, Republic of"
var -k country MC "Monaco"
var -k country MN "Mongolia"
var -k country ME "Montenegro"
var -k country MS "Montserrat"
var -k country MA "Morocco"
var -k country MZ "Mozambique"
var -k country MM "Myanmar"
var -k country NA "Namibia"
var -k country NR "Nauru"
var -k country NP "Nepal"
var -k country NL "Netherlands"
var -k country NC "New Caledonia"
var -k country NZ "New Zealand"
var -k country NI "Nicaragua"
var -k country NE "Niger"
var -k country NG "Nigeria"
var -k country NU "Niue"
var -k country NF "Norfolk Island"
var -k country MP "Northern Mariana Islands"
var -k country NO "Norway"
var -k country OM "Oman"
var -k country PK "Pakistan"
var -k country PW "Palau"
var -k country PS "Palestine, State of"
var -k country PA "Panama"
var -k country PG "Papua New Guinea"
var -k country PY "Paraguay"
var -k country PE "Peru"
var -k country PH "Philippines"
var -k country PN "Pitcairn"
var -k country PL "Poland"
var -k country PT "Portugal"
var -k country PR "Puerto Rico"
var -k country QA "Qatar"
var -k country RE "Réunion"
var -k country RO "Romania"
var -k country RU "Russian Federation"
var -k country RW "Rwanda"
var -k country BL "Saint Barthélemy"
var -k country SH "Saint Helena, Ascension and Tristan da Cunha"
var -k country KN "Saint Kitts and Nevis"
var -k country LC "Saint Lucia"
var -k country MF "Saint Martin (French part)"
var -k country PM "Saint Pierre and Miquelon"
var -k country VC "Saint Vincent and the Grenadines"
var -k country WS "Samoa"
var -k country SM "San Marino"
var -k country ST "Sao Tome and Principe"
var -k country SA "Saudi Arabia"
var -k country SN "Senegal"
var -k country RS "Serbia"
var -k country SC "Seychelles"
var -k country SL "Sierra Leone"
var -k country SG "Singapore"
var -k country SX "Sint Maarten (Dutch part)"
var -k country SK "Slovakia"
var -k country SI "Slovenia"
var -k country SB "Solomon Islands"
var -k country SO "Somalia"
var -k country ZA "South Africa"
var -k country GS "South Georgia and the South Sandwich Islands"
var -k country SS "South Sudan"
var -k country ES "Spain"
var -k country LK "Sri Lanka"
var -k country SD "Sudan"
var -k country SR "Suriname"
var -k country SJ "Svalbard and Jan Mayen"
var -k country SZ "Swaziland"
var -k country SE "Sweden"
var -k country CH "Switzerland"
var -k country SY "Syrian Arab Republic"
var -k country TW "Taiwan, Province of China"
var -k country TJ "Tajikistan"
var -k country TZ "Tanzania, United Republic of"
var -k country TH "Thailand"
var -k country TL "Timor-Leste"
var -k country TG "Togo"
var -k country TK "Tokelau"
var -k country TO "Tonga"
var -k country TT "Trinidad and Tobago"
var -k country TN "Tunisia"
var -k country TR "Turkey"
var -k country TM "Turkmenistan"
var -k country TC "Turks and Caicos Islands"
var -k country TV "Tuvalu"
var -k country UG "Uganda"
var -k country UA "Ukraine"
var -k country AE "United Arab Emirates"
var -k country GB "United Kingdom"
var -k country US "United States"
var -k country UM "United States Minor Outlying Islands"
var -k country UY "Uruguay"
var -k country UZ "Uzbekistan"
var -k country VU "Vanuatu"
var -k country VE "Venezuela, Bolivarian Republic of"
var -k country VN "Viet Nam"
var -k country VG "Virgin Islands, British"
var -k country VI "Virgin Islands, U.S."
var -k country WF "Wallis and Futuna"
var -k country EH "Western Sahara"
var -k country YE "Yemen"
var -k country ZM "Zambia"
var -k country ZW "Zimbabwe"